name: Docker Image Staging CD

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Publish project
      run: dotnet publish -c release
      working-directory: ./src/BikeDataProject.FileUpload/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bikedataproject/file-upload:staging
      working-directory: ./src/BikeDataProject.FileUpload/
    - name: Login to Docker Hub with Docker
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u anywaysopen --password-stdin
    - name: Publish the image to Docker Hub.
      run: docker push bikedataproject/file-upload:staging
      working-directory: ./src/BikeDataProject.FileUpload/
